<!-- Defining the footer section of the page -->
<footer id="footer">
  <section id="privacy">
  <div>
    Marcello Luciani &copy; <script>document.write(new Date().getFullYear())</script> - Cineplex
    </div>
    <a class="link" href="http://www.unife.it/">Universit&agrave; degli Studi di Ferrara</a> - <a class="link" href="http://www.unife.it/ing/informazione/sistemi-web">Ingegneria dei Sistemi Web</a>
  </section>
</footer>