--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2025-01-22 10:42:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "Ing_Soft";
--
-- TOC entry 4822 (class 1262 OID 17960)
-- Name: Ing_Soft; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Ing_Soft" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Italian_Italy.1252';


ALTER DATABASE "Ing_Soft" OWNER TO postgres;

\connect "Ing_Soft"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 18307)
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    type character varying(25) NOT NULL
);


ALTER TABLE public.category OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18306)
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18316)
-- Name: question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question (
    id bigint NOT NULL,
    content character varying(500),
    title character varying(300) NOT NULL,
    categ_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.question OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18315)
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18324)
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    id bigint NOT NULL,
    answer character varying(500),
    answered boolean DEFAULT false NOT NULL,
    title character varying(300) NOT NULL,
    categ_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 18323)
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 18232)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    last_login timestamp(6) without time zone
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 18231)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4812 (class 0 OID 18307)
-- Dependencies: 218
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.category VALUES (2, 'RESI');
INSERT INTO public.category VALUES (1, 'CAT. NON PRESENTE');
INSERT INTO public.category VALUES (3, 'SPEDIZIONE');
INSERT INTO public.category VALUES (4, 'ORDINI');


--
-- TOC entry 4814 (class 0 OID 18316)
-- Dependencies: 220
-- Data for Name: question; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.question VALUES (1, 'I tempi di spedizione variano a seconda della destinazione e del tipo di spedizione scelto. In genere, la consegna standard impiega 3-5 giorni lavorativi, mentre quella express arriva in 1-2 giorni. Al momento della spedizione, riceverai un’email con un link per monitorare il tuo ordine in tempo reale. Per ulteriori dettagli o se riscontri problemi, contatta il nostro servizio clienti.', 'Quali sono i tempi di spedizione e come posso monitorare il mio ordine?', 3, 1);
INSERT INTO public.question VALUES (2, 'Come indicato nei ´Termini e Condizioni di Acquisto´ il rimborso, sia esso nella forma monetaria che nella forma del voucher, verrà erogato al netto delle commissioni per i servizi d’intermediazione resi da UniTicket. Laddove eventualmente disposto dall’organizzatore il rimborso avverrà altresì al netto dei diritti di prevendita, che in ogni caso non potranno eccedere il 13% del prezzo complessivo del titolo di ingresso.
', 'Posso effettuare un reso?', 2, 1);


--
-- TOC entry 4816 (class 0 OID 18324)
-- Dependencies: 222
-- Data for Name: ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4810 (class 0 OID 18232)
-- Dependencies: 216
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."user" VALUES (1, 'admin@admin.it', 'Marcello', '$2a$10$NFauDcoeT1J..Cmc.W27Fe0J.75a3MqZ8yFKSnpu2gQ6.KWz5RrFy', 'ADMIN', '2024-11-07 16:53:01.4553');
INSERT INTO public."user" VALUES (2, 'marcello@gmail.com', 'Marcello', '$2a$10$NFauDcoeT1J..Cmc.W27Fe0J.75a3MqZ8yFKSnpu2gQ6.KWz5RrFy', 'USER', '2025-01-22 10:37:59.039744');


--
-- TOC entry 4823 (class 0 OID 0)
-- Dependencies: 217
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_seq', 4, true);


--
-- TOC entry 4824 (class 0 OID 0)
-- Dependencies: 219
-- Name: question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_id_seq', 2, true);


--
-- TOC entry 4825 (class 0 OID 0)
-- Dependencies: 221
-- Name: ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_id_seq', 1, false);


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 215
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 1, true);


--
-- TOC entry 4655 (class 2606 OID 18311)
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- TOC entry 4659 (class 2606 OID 18322)
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- TOC entry 4661 (class 2606 OID 18331)
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- TOC entry 4657 (class 2606 OID 18313)
-- Name: category uk_cat_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk_cat_type UNIQUE (type);


--
-- TOC entry 4651 (class 2606 OID 18284)
-- Name: user uk_user_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT uk_user_email UNIQUE (email);


--
-- TOC entry 4653 (class 2606 OID 18238)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 4662 (class 2606 OID 18352)
-- Name: question fk_question_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk_question_category FOREIGN KEY (categ_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;


--
-- TOC entry 4663 (class 2606 OID 18357)
-- Name: question fk_question_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk_question_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4664 (class 2606 OID 18362)
-- Name: ticket fk_ticket_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fk_ticket_category FOREIGN KEY (categ_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;


--
-- TOC entry 4665 (class 2606 OID 18367)
-- Name: ticket fk_ticket_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2025-01-22 10:42:01

--
-- PostgreSQL database dump complete
--

